give @s ac:amxmagic
give @s ac:amxgun
give @s pa:amxstick
give @s pa:amxdmdblack_four
give @s ac:amxsword
give @s ac:amxsk
give @s pa:amxcm
give @s pa:amxswordsmall
give @s pa:amxdmdblack_two
give @s pa:amxdmdblack_five
give @s pa:amxblackdmd_one
give @s pa:amxblackdmd
give @s ac:anmuxi
give @s pa:amxchui
give @s ac:amxmao
give @s pa:amxdmdblack_there
give @s ac:amxmkd
give @s ac:amxpickaxe
give @s ac:amxheavytool
give @s ac:amxchu
give @s ac:amxchan
give @s ac:amxding
give @s ac:yiqianmuxi2020
give @s ac:amxaxe
